# Generated by Django 5.2.10 on 2026-01-28 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_classroommembership_unique_together_and_more'),
        ('teacher', '0002_alter_submission_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='guideline',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classroom',
            name='attempts_allowed',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='classroom',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='classroom',
            name='format_check_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='plagiarism_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='penalty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('EVALUATED', 'Evaluated')], db_index=True, default='SUBMITTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='student.student'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['classroom'], name='teacher_sub_classro_d18d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student'], name='teacher_sub_student_a46cda_idx'),
        ),
        migrations.AddConstraint(
            model_name='guideline',
            constraint=models.UniqueConstraint(fields=('classroom', 'version'), name='unique_guideline_version'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('classroom', 'student', 'attempt_no'), name='unique_attempt_per_student'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
