# Generated by Django 5.2.10 on 2026-01-31 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_batch_options_batch_academic_year_and_more'),
        ('teacher', '0003_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.batch'),
        ),
    ]
