# Generated by Django 5.2.10 on 2026-02-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_classroom_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='guideline_file',
        ),
    ]
