# Generated by Django 5.2.10 on 2026-02-02 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_classroom_guideline_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='guidelines/drafts/')),
                ('extracted_rules', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_drafts', to='teacher.classroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
