# Generated by Django 5.2.10 on 2026-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_guidelinedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='breakdown_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
