# Generated by Django 5.2.10 on 2026-02-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_submission_breakdown_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='annotated_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/annotated/'),
        ),
    ]
