# Generated by Django 5.2.10 on 2026-02-12 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_student_stu_batch_i_77488c_idx'),
        ('teacher', '0008_submission_annotated_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='rules_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='rules_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.batch'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='breakdown_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('ERROR', 'Error'), ('EVALUATED', 'Evaluated')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['batch'], name='teacher_cla_batch_i_e1f3ef_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher'], name='teacher_cla_teacher_69e1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='teacher_sub_submitt_3daf98_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'classroom'], name='teacher_sub_student_3db09b_idx'),
        ),
    ]
