# Generated by Django 5.2.10 on 2026-02-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_classroom_rules_confirmed_classroom_rules_json_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guideline',
        ),
    ]
