# Generated by Django 5.2.10 on 2026-02-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_delete_guideline'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='rules_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
