# Generated by Django 5.2.10 on 2026-02-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_classroom_rules_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='guideline_file',
            field=models.FileField(blank=True, null=True, upload_to='guidelines/'),
        ),
    ]
