# Generated by Django 5.2.10 on 2026-03-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_classroom_guideline_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='guideline_file',
            field=models.FileField(blank=True, help_text='Legacy field retained for DB compatibility.', null=True, upload_to='guidelines/'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='rules_confirmed',
            field=models.BooleanField(default=False, help_text='Legacy confirmation flag (non-critical).'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='rules_json',
            field=models.JSONField(blank=True, help_text='Stores structured compliance rules.', null=True),
        ),
    ]
