# Generated by Django 5.2.10 on 2026-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_alter_classroom_guideline_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_percentage',
            field=models.FloatField(blank=True, help_text='Final computed percentage (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when marks were finalized', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
