# Generated by Django 5.2.10 on 2026-01-31 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email_alter_user_role'),
        ('student', '0005_alter_batch_options_batch_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='student.batch')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['teacher'], name='accounts_te_teacher_ca2abf_idx'), models.Index(fields=['batch'], name='accounts_te_batch_i_4c962c_idx')],
                'unique_together': {('teacher', 'batch')},
            },
        ),
    ]
