# Generated by Django 5.2.10 on 2026-03-03 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, choices=[('LECTURER', 'Lecturer'), ('ASSISTANT_PROF', 'Assistant Professor'), ('ASSOCIATE_PROF', 'Associate Professor'), ('PROFESSOR', 'Professor')], max_length=30)),
                ('highest_qualification', models.CharField(blank=True, max_length=150)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('qualification_institution', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
