# Generated by Django 5.2.10 on 2026-01-29 04:39

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_classroommembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-academic_year', 'name']},
        ),
        migrations.AddField(
            model_name='batch',
            name='academic_year',
            field=models.CharField(default=student.models.current_academic_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'academic_year')},
        ),
    ]
