# Generated by Django 5.2.10 on 2026-02-12 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_batch_options_batch_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['batch'], name='student_stu_batch_i_77488c_idx'),
        ),
    ]
