# Generated by Django 5.2.10 on 2026-02-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_student_stu_batch_i_77488c_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='register_no',
        ),
    ]
