# Generated by Django 5.2.10 on 2026-02-22 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_student_options_remove_student_register_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroommembership',
            name='unlock_note',
            field=models.TextField(blank=True, help_text='Teacher decision note (optional)'),
        ),
        migrations.AddField(
            model_name='classroommembership',
            name='unlock_until',
            field=models.DateTimeField(blank=True, help_text='Temporary personal unlock window', null=True),
        ),
        migrations.AddField(
            model_name='classroommembership',
            name='unlocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_unlocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unlockrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_unlock_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
